apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tomcat
  name: my-tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: 811636332895.dkr.ecr.ap-southeast-1.amazonaws.com/tomcat
        ports:
         - containerPort: 8090

